import { randomUUID } from "node:crypto";
import { z } from "zod";
import { groqChat } from "@poststreak/integrations/groq";
import { jarvisChatPrompt } from "./prompts";

// ============================================================================
// Jarvis chat — the "Ask Jarvis" panel
//
// Replaces src/jarvis/chat.ts `think()` (keyword-matched canned replies). The
// reply keeps the exact shape the app already renders, so Ghost's job buttons
// keep working unchanged:
//   { text, ideas?, caption?, list?, tasks?, chips? }   (+ optional `emotion`)
//
// Trust model: the model only SUGGESTS. Everything it returns is parsed,
// validated, length-capped and rebuilt here before it reaches the app:
//   - ids are generated by the server, never taken from the model;
//   - Ghost job labels / confirmations come from templates, so model text can't
//     masquerade as an action label;
//   - only allow-listed job kinds and pages survive (a made-up page is dropped);
//   - one bad part (a malformed idea) is dropped without losing the whole reply.
// If the model is down or unusable, the creator gets a gentle fallback reply,
// never a stack trace.
// ============================================================================

/** Pages Ghost can take the creator to. Mirrors `GhostPlace` in src/jarvis/chat.ts. */
export const GHOST_PLACES = [
  "create",
  "schedule",
  "growth",
  "repurpose",
  "hook-studio",
  "quests",
  "challenge",
  "jarvis-pro",
  "accounts",
] as const;
export type GhostPlace = (typeof GHOST_PLACES)[number];

/** Ghost's 12 expressions. Mirrors `Emotion` in src/mascot/mascot.ts and the ghost_emotion DB enum. */
export const GHOST_EMOTIONS = [
  "wave",
  "happy",
  "excited",
  "party",
  "love",
  "cool",
  "thinking",
  "idea",
  "working",
  "determined",
  "sleepy",
  "calm",
] as const;
export type GhostEmotion = (typeof GHOST_EMOTIONS)[number];

export const START_CHIPS = [
  "Give me post ideas",
  "Write me a caption",
  "When should I post?",
  "How do I grow?",
];

const PLACE_NAME: Record<GhostPlace, string> = {
  create: "Create",
  schedule: "your Schedule",
  growth: "Growth",
  repurpose: "Repurpose",
  "hook-studio": "Hook Studio",
  quests: "Quests",
  challenge: "this week’s challenge",
  "jarvis-pro": "Pro",
  accounts: "your accounts",
};

// ─── What goes out (matches src/jarvis/chat.ts) ─────────────────────────────

export type GhostJob =
  | { kind: "compose"; title: string }
  | { kind: "draft"; title: string; format: string }
  | { kind: "open"; place: GhostPlace }
  | { kind: "copy"; text: string }
  | { kind: "checkIn" };

export type GhostTask = {
  id: string;
  /** What the creator taps, e.g. "Ghost, save it to drafts" */
  label: string;
  /** What Ghost says when done, e.g. "Saved to your drafts" */
  done: string;
  job: GhostJob;
};

export type FeedIdea = {
  id: string;
  niche: string;
  title: string;
  hook: string;
  format: string;
  bestTime: string;
  why: string;
};

export type JarvisReply = {
  text: string;
  ideas?: FeedIdea[];
  caption?: string;
  list?: string[];
  tasks?: GhostTask[];
  chips?: string[];
  emotion?: GhostEmotion;
};

// ─── What comes in ──────────────────────────────────────────────────────────

export const jarvisChatInputSchema = z.object({
  message: z.string().trim().min(1).max(600),
  /** The last few turns, oldest first, so Jarvis can follow the conversation. */
  history: z
    .array(z.object({ from: z.enum(["me", "jarvis"]), text: z.string().max(900) }))
    .max(8)
    .default([]),
  context: z
    .object({
      persona: z.enum(["new", "returning"]).default("new"),
      niches: z.array(z.string().max(40)).max(12).default([]),
      platforms: z.array(z.string().max(20)).max(8).default([]),
      lastTopic: z.string().max(120).optional(),
    })
    .default({}),
});
export type JarvisChatInput = z.infer<typeof jarvisChatInputSchema>;

// ─── Sanitising the model's output ──────────────────────────────────────────

/** Truncates by code point, so emoji are never split in half. */
const clip = (value: string, max: number) => {
  const chars = Array.from(value.trim());
  return chars.length <= max ? chars.join("") : chars.slice(0, max).join("").trimEnd();
};

const str = (max: number) => z.string().transform((s) => clip(s, max)).pipe(z.string().min(1));

const ideaSchema = z.object({
  title: str(120),
  hook: str(240),
  format: str(40).optional().catch(undefined),
  bestTime: str(20).optional().catch(undefined),
  why: str(160).optional().catch(undefined),
});

const taskSchema = z.discriminatedUnion("kind", [
  z.object({ kind: z.literal("open"), place: z.enum(GHOST_PLACES) }),
  z.object({ kind: z.literal("compose"), title: str(120) }),
  z.object({ kind: z.literal("draft"), title: str(120), format: str(40).optional().catch(undefined) }),
  z.object({ kind: z.literal("copy"), text: str(2200) }),
  z.object({ kind: z.literal("checkIn") }),
]);

type Deps = {
  complete?: CompleteFn;
  newId?: () => string;
};

/** Parts of a model object that are bad are dropped, not fatal. */
function parts<S extends z.ZodTypeAny>(raw: unknown, schema: S, max: number): z.output<S>[] {
  if (!Array.isArray(raw)) return [];
  const out: z.output<S>[] = [];
  for (const item of raw) {
    const parsed = schema.safeParse(item);
    if (parsed.success) out.push(parsed.data);
    if (out.length >= max) break;
  }
  return out;
}

function buildTask(job: GhostJob, id: string, hasCaption: boolean): GhostTask {
  switch (job.kind) {
    case "open":
      return {
        id,
        label: `Ghost, open ${PLACE_NAME[job.place]}`,
        done: job.place === "accounts" ? "Opened your accounts" : `Opened ${PLACE_NAME[job.place]}`,
        job,
      };
    case "compose":
      return { id, label: "Ghost, start this post", done: "Your post is ready to edit", job };
    case "draft":
      return { id, label: "Ghost, save it to drafts", done: "Saved to your drafts", job };
    case "copy":
      return {
        id,
        label: hasCaption ? "Ghost, copy the caption" : "Ghost, copy this",
        done: "Copied. Paste it anywhere",
        job,
      };
    case "checkIn":
      return { id, label: "Ghost, check me in for today", done: "Checked in for today", job };
  }
}

/**
 * Turns whatever the model returned into a safe JarvisReply, or null when it
 * has no usable `text` (the caller then retries or falls back).
 */
export function sanitizeReply(
  raw: unknown,
  opts: { niche: string; newId: () => string },
): JarvisReply | null {
  if (typeof raw !== "object" || raw === null) return null;
  const obj = raw as Record<string, unknown>;

  const text = str(900).safeParse(obj.text);
  if (!text.success) return null;

  const reply: JarvisReply = { text: text.data };

  const ideas = parts(obj.ideas, ideaSchema, 3).map((i) => ({
    id: `i-${opts.newId()}`,
    niche: opts.niche,
    title: i.title,
    hook: i.hook,
    format: i.format ?? "30-second Reel",
    bestTime: i.bestTime ?? "7:30 PM",
    why: i.why ?? "Fits what you make.",
  }));
  if (ideas.length) reply.ideas = ideas;

  const caption = str(2200).safeParse(obj.caption);
  if (caption.success) reply.caption = caption.data;

  const list = parts(obj.list, str(240), 5);
  if (list.length) reply.list = list;

  const tasks = parts(obj.tasks, taskSchema, 2).map((parsed) => {
    const job: GhostJob =
      parsed.kind === "draft" ? { kind: "draft", title: parsed.title, format: parsed.format ?? "Post" } : parsed;
    return buildTask(job, `t-${opts.newId()}`, reply.caption !== undefined);
  });
  if (tasks.length) reply.tasks = tasks;

  const chips = parts(obj.chips, str(60), 3);
  if (chips.length) reply.chips = chips;

  const emotion = z.enum(GHOST_EMOTIONS).safeParse(obj.emotion);
  if (emotion.success) reply.emotion = emotion.data;

  return reply;
}

/**
 * Pulls the first well-formed JSON object out of a model reply. Models often
 * wrap it in code fences or add a sentence before or after it, so this scans
 * for balanced braces (aware of strings and escapes) from each "{" until one
 * parses, rather than trusting the first "{" and last "}" to enclose it.
 */
export function extractJson(text: string): unknown {
  for (let start = text.indexOf("{"); start !== -1; start = text.indexOf("{", start + 1)) {
    let depth = 0;
    let inString = false;
    for (let i = start; i < text.length; i++) {
      const c = text[i];
      if (inString) {
        if (c === "\\") i++;
        else if (c === '"') inString = false;
        continue;
      }
      if (c === '"') inString = true;
      else if (c === "{") depth++;
      else if (c === "}" && --depth === 0) {
        try {
          const parsed: unknown = JSON.parse(text.slice(start, i + 1));
          if (typeof parsed === "object" && parsed !== null && !Array.isArray(parsed)) return parsed;
        } catch {
          // Not valid JSON from this "{"; try the next one.
        }
        break;
      }
    }
  }
  return null;
}

// ─── Calling the model ──────────────────────────────────────────────────────

export type CompleteFn = (args: {
  system: string;
  messages: { role: "user" | "assistant"; content: string }[];
  temperature: number;
  maxTokens: number;
}) => Promise<string>;

/** Groq first, Gemini as the fallback (packages/integrations/groq.ts). */
const defaultComplete: CompleteFn = async ({ system, messages, temperature, maxTokens }) => {
  const out: unknown = await groqChat({
    messages: [{ role: "system", content: system }, ...messages],
    temperature,
    // Groq's default model reasons before answering; leave headroom so it
    // doesn't spend the whole budget thinking and return nothing.
    max_tokens: maxTokens,
  });
  if (typeof out !== "string") throw new Error("Jarvis model returned a non-text response");
  return out;
};

/** Appends the retry instruction to the last user turn (providers differ on consecutive user turns). */
function withRepairNote(messages: { role: "user" | "assistant"; content: string }[]) {
  const note = "\n\n(Reply again with only the JSON object described above, nothing else.)";
  return messages.map((m, i) => (i === messages.length - 1 ? { ...m, content: m.content + note } : m));
}

export const FALLBACK_REPLY: JarvisReply = {
  text: "I’m having trouble thinking right now. Give me a moment and try again.",
  chips: START_CHIPS,
  emotion: "thinking",
};

export type JarvisChatResult = {
  reply: JarvisReply;
  /** True when this is the fallback reply, not a model answer. */
  degraded: boolean;
};

export async function jarvisChat(input: JarvisChatInput, deps: Deps = {}): Promise<JarvisChatResult> {
  const complete = deps.complete ?? defaultComplete;
  const newId = deps.newId ?? (() => randomUUID().slice(0, 8));

  const { system, temperature } = jarvisChatPrompt({
    persona: input.context.persona,
    niches: input.context.niches,
    platforms: input.context.platforms,
    lastTopic: input.context.lastTopic,
    places: GHOST_PLACES,
    emotions: GHOST_EMOTIONS,
  });

  const messages = [
    ...input.history.map((h) => ({
      role: h.from === "me" ? ("user" as const) : ("assistant" as const),
      content: h.text,
    })),
    { role: "user" as const, content: input.message },
  ];

  const niche = input.context.niches[0] ?? "lifestyle";

  // One retry if the model answers but not in a usable shape. A provider
  // failure (both Groq and the Gemini fallback down) is not retried.
  for (let attempt = 0; attempt < 2; attempt++) {
    let text: string;
    try {
      text = await complete({
        system,
        messages: attempt === 0 ? messages : withRepairNote(messages),
        temperature,
        maxTokens: 1400,
      });
    } catch (err) {
      console.error("Jarvis chat model call failed:", err instanceof Error ? err.message : err);
      return { reply: FALLBACK_REPLY, degraded: true };
    }

    const reply = sanitizeReply(extractJson(text), { niche, newId });
    if (reply) return { reply, degraded: false };
  }

  return { reply: FALLBACK_REPLY, degraded: true };
}
