// ============================================================================
// Workflow: Mission Lifecycle
// STUB — structural placeholder only. No implementation yet.
// Governed by: packages/workflows/WORKFLOWS.md
// ============================================================================
//
// 1. Home loads -> missions.today (packages/api/routers/missions.ts) ->
//    packages/ai/mission-recommender.ts. Generated on-demand and cached
//    for the rest of the WAT day (founder-confirmed, Stage 5) — not
//    pre-generated by a cron sweep.
// 2. User starts / replaces / reschedules / simplifies / completes.
// 3. On completion: writes a streak_event. Mission completion now
//    advances the same streak counter a publish does (founder-confirmed,
//    Stage 5 — see WORKFLOWS.md for the tradeoff this overrides).
// ============================================================================
