-- ============================================================================
-- Migration: User Sanctions & Account Status
-- STUB — structural placeholder only. No implementation SQL yet.
-- Governed by: supabase/DATA_MODEL.md
-- ============================================================================
--
-- ADDED DURING STAGE 6 (ADMIN DASHBOARD LAYER) — Stage 1's users table only
-- had a generic status field. Doc3 requires staff to search/verify/
-- suspend/restrict/warn users and review their history (§23); that needs
-- real states and an audit trail, not a free-text status column.
--
-- Modeled as a NEW migration altering the original table, not an edit to
-- 20260814000001_accounts_and_identity.sql — once a migration is
-- "shipped" (Stage 1 was approved), the honest way to change it is a
-- follow-up migration, the same discipline a real Supabase project needs.
--
-- Intended scope:
--   - ALTER users: status becomes a real enum — active | warned |
--     restricted | suspended | closed.
--   - `user_sanctions`: append-only log — user_id, action, reason,
--     issued_by (staff user_id), issued_at, expires_at (nullable, for
--     time-boxed restrictions). This is the audit trail doc3's security
--     baseline (§65) calls for.
--
-- Relationships:
--   - user_sanctions.user_id -> users.id
--   - user_sanctions.issued_by -> users.id (must hold the staff_admin role)
-- ============================================================================
