-- ============================================================================
-- Migration: Billing & Subscriptions
-- STUB — structural placeholder only. No implementation SQL yet.
-- Governed by: supabase/DATA_MODEL.md
-- ============================================================================
--
-- Intended scope:
--   - `subscription_plans`: tier catalog. NAMES AND PRICES ARE DISPUTED
--     between source docs — Free/Pro ₦2,999 ($7)/Growth ₦9,999 ($19) in the
--     Architecture Doc, vs. Creator/Growth/Automation (a third paid tier)
--     at different USD prices for the same NGN anchors in the Creator
--     Engine Strategy. Do not seed real rows until resolved.
--     (DATA_MODEL.md item A.)
--   - `subscriptions`: one active row per user, references a plan.
--     `processor` ('paystack' | 'stripe') and `currency` as discriminator
--     columns on a single table, rather than separate tables per processor
--     — recommended default, not yet confirmed. (DATA_MODEL.md item E.)
--   - `payment_transactions`: processor-specific metadata in a jsonb
--     column; core amount/currency/status fields stay processor-agnostic.
--
-- Relationships:
--   - subscriptions.user_id -> users.id
--   - subscriptions.plan_id -> subscription_plans.id
--   - payment_transactions.subscription_id -> subscriptions.id
-- ============================================================================
