-- ============================================================================
-- Migration: Analytics Events
-- STUB — structural placeholder only. No implementation SQL yet.
-- Governed by: supabase/DATA_MODEL.md
-- ============================================================================
--
-- Intended scope:
--   - `analytics_events`: generic append-only event log — user_id,
--     event_name, properties (jsonb), created_at. Event taxonomy drafted in
--     Post_Streak_App 2.md §33 (acquisition, activation, mission, content,
--     discovery, collaboration, safety, retention).
--
-- Deliberately one generic table rather than one table per event type —
-- keeps this migration stable as the event taxonomy grows across every
-- other domain in this migration set.
-- ============================================================================
