-- ============================================================================
-- Migration: Social Platform Connections & Scheduling
-- STUB — structural placeholder only. No implementation SQL yet.
-- Governed by: supabase/DATA_MODEL.md
-- ============================================================================
--
-- Intended scope:
--   - `platform_connections`: one row per (user, platform). X and LinkedIn
--     now; Meta and TikTok planned. Stores auth/token metadata per platform.
--   - `scheduled_posts`: composed content + target platform(s) + schedule
--     time + status.
--   - `publish_mode` on platform_connections: 'api' | 'assisted'. X is
--     'assisted' today (PostStreak prepares the post, the user completes
--     it manually); LinkedIn is 'api' (true auto-post). This lets a
--     platform's automation level change later without a schema migration.
--     Recommended default — not yet confirmed by the team (DATA_MODEL.md
--     item C).
--
-- Relationships:
--   - platform_connections.user_id -> users.id
--   - scheduled_posts.user_id -> users.id
--   - scheduled_posts references one or more platform_connections
--   - A successful publish is what streak_events (streak_jarvis_gamification.sql)
--     treats as a qualifying action — generating or drafting content does not.
-- ============================================================================
