-- ============================================================================
-- Migration: Accounts & Identity
-- STUB — structural placeholder only. No implementation SQL yet.
-- Governed by: supabase/DATA_MODEL.md
-- ============================================================================
--
-- Intended scope:
--   - `users`: 1:1 with Supabase Auth (auth.users). Holds PostStreak-specific
--     fields Supabase Auth doesn't track itself — status, country, consent
--     flags, account-closure state.
--   - `creator_profiles`: bio, niche, city, languages, platform links,
--     collaboration intent, visibility flags. Feeds Creator Passport
--     (see creator_network.sql) rather than being a separate table for it.
--   - `roles`: 'creator' | 'staff_admin' for this pass only. Brand/agency
--     and service-professional roles are NOT modeled — the marketplace
--     pillars that need them are explicitly deferred (DATA_MODEL.md §2).
--
-- Relationships:
--   - creator_profiles.user_id -> users.id (1:1)
--   - Every other domain in this migration set hangs off users.id or
--     creator_profiles.id.
--
-- Open items (DATA_MODEL.md §3):
--   - RLS policy philosophy (item F) is undecided — no policies here yet.
--
-- UPDATED Stage 6: `users.status` is superseded by a real enum and a
-- companion audit-log table — see 20260814000011_user_sanctions.sql. Not
-- edited in place here; once a migration is approved it gets a follow-up
-- migration, not a rewrite, same discipline a real Supabase project needs.
-- ============================================================================
