-- ============================================================================
-- Migration: Voice Studio
-- STUB — structural placeholder only. No implementation SQL yet.
-- Governed by: supabase/DATA_MODEL.md
-- ============================================================================
--
-- Intended scope (sized to Creator Engine Strategy §03-04 metering model):
--   - `voice_projects`: script, chosen narrator/voice, status, linked
--     scheduled_post. Streak/credit reward fires on publish, not on
--     generation (Creator Engine Strategy retention rule: "do not reward
--     raw AI generations").
--   - `series_voices`: creator-saved narrator + pronunciation notes, reused
--     episode to episode.
--   - `voice_minutes_wallet`: included minutes for the current billing
--     period, derived from the active subscription_plan.
--   - `voice_minutes_ledger`: append-only debits (generation) and credits
--     (top-up, plan renewal). Wallet balance should be derived from this
--     ledger, never mutated directly.
--   - `voice_topups`: purchased minute packs outside the plan allowance.
--
-- Explicitly NOT included: Video Studio. It shares the "credit wallet"
-- shape conceptually, but Creator Engine Strategy §05 scopes it as
-- "build after voice." Deferred to a later DATA_MODEL revisit, tracked in
-- OPEN_QUESTIONS (Stage 8) rather than stubbed here. (DATA_MODEL.md item H.)
--
-- Relationships:
--   - voice_projects.user_id -> users.id
--   - voice_minutes_wallet.subscription_id -> subscriptions.id
--     (billing_and_subscriptions.sql)
-- ============================================================================
