-- ============================================================================
-- Migration: Creator Network (Matching, Collaboration, Squads, Passport)
-- STUB — structural placeholder only. No implementation SQL yet.
-- Governed by: supabase/DATA_MODEL.md
-- ============================================================================
--
-- Confirmed in scope for this rebuild (founder decision, 2026-08-14):
-- Matching/Discovery, Collaboration Workspace, Squads/Community, Creator
-- Passport. Brand/Agency platform, Opportunity Marketplace, Creator
-- Services Marketplace, and Payments/Contracts/Escrow are explicitly
-- DEFERRED — do not model those here (DATA_MODEL.md §2).
--
-- Intended scope (entity list adapted from Post_Streak_App 2.md §30):
--   - `discovery_actions`: viewed | passed | saved | interested |
--     priority_requested. actor -> target, one row per action.
--   - `matches`: created when both sides express interest. status + timestamps.
--   - `conversations` / `messages`: scoped to a match. Moderation state per
--     message hooks into safety_and_moderation.sql.
--   - `collaboration_briefs`: concept, roles, deliverables, dates, status
--     (proposed -> accepted -> scheduled -> active -> completed | cancelled
--     | disputed).
--   - `collaboration_tasks`: sub-items on a brief (writing, filming, editing,
--     posting, reporting) with owners.
--   - `squads`: city | niche | stage | language squads; `squad_members`;
--     squad-leader role.
--   - Creator Passport: likely a visibility flag + slug on creator_profiles
--     plus a read-model aggregating profile + streak + completed
--     collaborations, rather than its own table. Not yet decided whether it
--     needs dedicated storage — revisit at BACKEND_ARCHITECTURE.
--
-- Relationships:
--   - discovery_actions, matches: creator_profiles.id <-> creator_profiles.id
--   - collaboration_briefs -> matches.id
--   - squad_members -> squads.id, users.id
--
-- Open items:
--   - RLS philosophy (DATA_MODEL.md item F) matters most here — this is the
--     first domain with real cross-user reads (leaderboards, squad rosters,
--     discovery feeds) that plain owner-only RLS doesn't handle.
-- ============================================================================
