-- ============================================================================
-- Migration: Duels
-- STUB — structural placeholder only. No implementation SQL yet.
-- Governed by: supabase/DATA_MODEL.md
-- ============================================================================
--
-- ADDED DURING STAGE 5 (WORKFLOWS) — not one of the four Creator Network
-- pillars confirmed in Stage 1 (Matching, Collaboration Workspace, Squads,
-- Passport). Founders confirmed separately it's in scope. Same pattern as
-- the missions.sql addition in Stage 3 — flagging plainly rather than
-- rewriting Stage 1's history.
--
-- Intended scope:
--   - `duels`: paired user_a_id/user_b_id, start/end date, status (active |
--     completed | cancelled), reward definition. No "failed" status —
--     RESOLVED Stage 8: a missed shared-completion day skips only that
--     day's reward, it doesn't end the duel. A duel only ends via window
--     expiry (completed) or explicit cancellation.
--
-- Deliberately NO separate progress-tracking table: whether each partner
-- had a qualifying action on a given day is read from their own
-- streak_events rows (streak_jarvis_gamification.sql) — a duel is a lens
-- over existing streak data, not a parallel tracking system.
--
-- Relationships:
--   - duels.user_a_id / duels.user_b_id -> users.id
-- ============================================================================
