-- ============================================================================
-- Migration: Missions (Daily Recommendation System)
-- STUB — structural placeholder only. No implementation SQL yet.
-- Governed by: supabase/DATA_MODEL.md
-- ============================================================================
--
-- ADDED DURING STAGE 3 (FRONTEND_ARCHITECTURE) — Post_Streak_App 2.md's
-- Home screen concept surfaced a gap: the "daily mission" system (§10-11)
-- wasn't one of the four Creator Network pillars confirmed in Stage 1, but
-- the founders confirmed separately that it's in scope once this stage's
-- questions raised it. This migration was not part of the original Stage 1
-- pass — flagging that plainly rather than rewriting Stage 1's history.
--
-- Intended scope:
--   - `missions`: type (ideation | production | publishing | engagement |
--     collaboration | growth_experiment | business | recovery — category
--     list from Post_Streak_App 2.md §10), instructions, target date,
--     difficulty, status (pending | started | completed | replaced |
--     rescheduled | simplified), source.
--   - May link forward to a scheduled_post (social_scheduling.sql) or a
--     collaboration_brief (creator_network.sql) once acted on.
--
-- Explicitly NOT this migration's job: the recommendation logic that
-- decides WHICH mission a given creator sees on a given day. That's Stage
-- 4 (AI ORCHESTRATION) work — this table only reserves the storage shape.
-- Product guardrails from the source doc worth carrying into that later
-- work: never claim a mission guarantees views/followers; don't force
-- daily publishing when a realistic schedule is lower.
--
-- Relationships:
--   - missions.user_id -> users.id
-- ============================================================================
