-- ============================================================================
-- Migration: Safety & Moderation
-- STUB — structural placeholder only. No implementation SQL yet.
-- Governed by: supabase/DATA_MODEL.md
-- ============================================================================
--
-- Added because Matching/Discovery and Collaboration Workspace are now in
-- scope (creator_network.sql) — shipping creator-to-creator discovery
-- without block/report/moderation is not a safe baseline
-- (Post_Streak_App 2.md §23, §28, §34 treat this as non-optional wherever
-- matching exists).
--
-- Intended scope:
--   - `blocks`: user -> user. Hides both directions from discovery/match.
--   - `reports`: reporter, target, category, evidence, status, severity.
--   - `moderation_actions`: staff action taken on a report, audit trail.
--
-- Relationships:
--   - All key off users.id / creator_profiles.id.
--   - reports.target may point at a user, a message, or a collaboration —
--     exact polymorphic reference shape TBD at BACKEND_ARCHITECTURE.
-- ============================================================================
