-- ============================================================================
-- Migration: Streak, Jarvis & Gamification
-- STUB — structural placeholder only. No implementation SQL yet.
-- Governed by: supabase/DATA_MODEL.md
-- ============================================================================
--
-- Intended scope:
--   - `streak_states`: current streak count, weekly target, last qualifying
--     day. MUST use the user's local calendar day (Africa/Lagos, WAT), not
--     UTC — the WAT streak-boundary bug is already fixed in the live
--     product; this schema must not regress it.
--   - `streak_events`: append-only log of qualifying actions per day.
--   - `jarvis_emotion_state`: enum/lookup. Value count is DISPUTED between
--     source docs — 9 states (Architecture Doc, matches founder ground
--     truth) vs. 8 states (Creator Engine Strategy). NOT resolved.
--     Placeholder only — do not hardcode a count. (DATA_MODEL.md item B.)
--   - `streak_freezes`: mechanic is UNDECIDED between three shapes —
--     (1) spent from the existing credit ledger, (2) a separate
--     subscription-tier entitlement counter, (3) milestone-earned only,
--     never purchasable. Structural placeholder only. (DATA_MODEL.md item D.)
--   - `credits`: ledger of credit-earning events (streak milestones) and
--     redemptions. Already live per the Architecture Doc — this table
--     formalizes existing behavior, doesn't introduce new behavior.
--   - `milestones` / `badges`: 7-day, 30-day, 100-post style thresholds.
--
-- Relationships:
--   - All tables key off users.id.
--   - streak_events rows are written by multiple sources — UPDATED Stage 5:
--     founders chose to expand qualifying actions beyond publish-only.
--     Sources: the publish pipeline (social_scheduling.sql), mission
--     completion (missions.sql, via packages/workflows/mission-lifecycle.ts),
--     and collaboration completion (creator_network.sql, via
--     packages/workflows/collaboration-lifecycle.ts). This deliberately
--     overrides Creator Engine Strategy's stricter "publish-only" rule —
--     see packages/workflows/WORKFLOWS.md for the reasoning and the
--     abuse-risk caveat carried forward from that source doc.
--   - duels.sql reads this table (not a separate progress table) to check
--     each duel partner's daily qualifying-action status.
-- ============================================================================
